webserver/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'login/$', views.userLogin, name='login'),
    url(r'logout/$', views.userLogout, name='logout'),
    url(r'loginmobile/$', views.userLoginMobile, name='loginMobile'),

    url(r'desaparecidos/$', views.desaparecidos, name='desaparecidos'),
    url(r'desaparecidos/cadastrar/$', views.cadastrarDesaparecido, name='cadastrarDesaparecido'),
    url(r'desaparecidos/editar/(?P<pk>\d+)/$', views.editarDesaparecido, name='editarDesaparecido'),
    url(r'desaparecidos/visualizar/(?P<pk>\d+)/$', views.visualizarDesaparecido, name='visualizarDesaparecido'),
    url(r'desaparecidos/remover/(?P<pk>\d+)/$', views.removerDesaparecido, name='removerDesaparecido'),
    url(r'desaparecidos/buscarDesaparecido/$', views.buscarDesaparecido, name='buscarDesaparecido'),
    url(r'desaparecidos/buscarDesaparecidoWeb/$', views.buscarDesaparecidoWeb, name='buscarDesaparecidoWeb'),
    url(r'desaparecidos/getFaceEcoding/$', views.getFaceEcoding, name='getFaceEcoding'),
    url(r'desaparecidos/gerarCartaz/(?P<pk>\d+)/$', views.gerarCartaz, name='gerarCartaz'),
    url(r'desaparecidos/editarNomeCartazete/(?P<pk>\d+)/$', views.editarNomeCartazete, name='editarNomeCartazete'),

    url(r'usuarios/$', views.usuarios, name='usuarios'),
    url(r'usuarios/cadastrar/$', views.cadastrarUsuario, name='cadastrarUsuario'),
    url(r'usuarios/editar/(?P<pk>\d+)/$', views.editarUsuario, name='editarUsuario'),
    url(r'usuarios/visualizar/(?P<pk>\d+)/$', views.visualizarUsuario, name='visualizarUsuario'),
    url(r'usuarios/remover/(?P<pk>\d+)/$', views.removerUsuario, name='removerUsuario'),
]

webserver/models.py
from django.db import models
from django.contrib.auth.models import User


# Query manager alternativo para buscar apenas itens query manager
class OnlyActive(models.Manager):
    def get_queryset(self):
        return super(OnlyActive, self).get_queryset().filter(is_active=True)

# Create your models here.
class Pessoa(models.Model):
    
    # default manager
    objects = models.Manager()
    # custom
    actives = OnlyActive()



    FAIXA_IDADE = (
        ("ate_18_anos", "Até 18 anos"),
        ("de_19_ate_30_anos", "De 19 até 30 anos"),
        ("de_31_ate_45_anos", "De 31 até 45 anos"),
        ("de_46_ate_65_anos", "De 46 até 65 anos"),
        ("acima_de_65_anos", "Acima de 65 anos"),
    )   

    FAIXA_ALTURA = (
        ("anao", "Anão"),
        ("ate_160", "Até 1,60 m"),
        ("de_160_ate_170", "De 1,60 até 1,70 m"),
        ("de_170_ate_180", "De 1,70 até 1,80 m"),
        ("acima_de_180", "Acima de 1,80 m"),
    )

    SEXO = (
        ("masculino", "Masculino"),
        ("feminino", "Feminino"),
    )   

    COR_PELE = (
        ("albino", "Albino"),
        ("amarela", "Amarela"),
        ("branca", "Branca"),
        ("negra", "Negra"),
        ("parda", "Parda"),
        ("vermelha", "Vermelha"),
    )

    COR_OLHOS = (
        ("azuis", "Azuis"),
        ("castanhos_claros", "Castanhos Claros"),
        ("castanhos_escuros", "Castanhos Escuros"),
        ("cinzentos", "Cinzentos"),
        ("castanhos", "Castanhos"),
        ("desiguais_na_cor", "Desiguais na Cor"),
        ("pretos", "Pretos"),
        ("verdes", "Verdes"),
        ("violetas", "Violetas"),
    )

    COR_CABELOS = (
        ("aco", "Aço"),
        ("branco", "Branco"),
        ("castanho_claro", "Castanho Claro"),
        ("castanho_escuro", "Castanho Escuro"),
        ("com_mechas_ou_faixas", "Com Mechas ou Faixas"),
        ("louro", "Louro"),
        ("preto", "Preto"),
        ("ruivo", "Ruivo")
    )

    TIPO_FISICO = (
        ("magro", "Magro"),
        ("normal", "Normal"),
        ("gordo", "Gordo"),
        ("forte", "Forte"),
    )

    nome = models.CharField(max_length = 254, blank=True, null=True)
    nome_normalizado = models.CharField(max_length = 254, blank=True, null=True)
    idade = models.IntegerField(blank=True, null=True)
    idade_aparente = models.CharField(max_length = 100, choices = FAIXA_IDADE, blank=True, null=True)
    altura = models.IntegerField(blank=True, null=True)
    faixa_altura = models.CharField(max_length = 100, choices = FAIXA_ALTURA, blank=True, null=True)
    cor_pele = models.CharField(max_length = 100, choices = COR_PELE, blank=True, null=True)
    cor_olhos = models.CharField(max_length = 100, choices = COR_OLHOS, blank=True, null=True)
    cor_cabelos = models.CharField(max_length = 100, choices = COR_CABELOS, blank=True, null=True)
    sexo = models.CharField(max_length = 100, choices = SEXO, blank=True, null=True)
    nome_pai = models.CharField(max_length = 254, blank=True, null=True)
    nome_mae = models.CharField(max_length = 254, blank=True, null=True)
    foto = models.ImageField(upload_to = "fotos/", blank = True, null = True)
    facial_encoding = models.TextField(blank = True, null = True)
    encoding_distance_to_zero = models.FloatField(blank = True, null = True)
    data_nascimento = models.DateTimeField(blank=True, null=True)
    data_desaparecimento = models.DateTimeField(blank=True, null=True)
    local_desaparecimento = models.CharField(max_length = 254, blank=True, null=True)
    cartazete = models.ImageField(upload_to = "cartazetes/",blank = True, null = True)
    nome_no_cartazete = models.CharField(max_length = 254, blank=True, null=True)
    comentario_desaparecimento = models.TextField(blank = True, null = True)
    possui_tatuagem = models.NullBooleanField(blank=True, null=True)
    possui_cicatriz = models.NullBooleanField(blank=True, null=True)
    possui_deficiencia = models.NullBooleanField(blank=True, null=True)
    sofreu_amputacao = models.NullBooleanField(blank=True, null=True)
    esta_desaparecido = models.NullBooleanField(default=True, null=True)
    tipo_fisico = models.CharField(max_length = 254, choices = TIPO_FISICO, blank=True, null=True)

    # Para uso futuro
    rg = models.CharField(max_length = 9, blank=True, null=True)
    emissor_rg = models.CharField(max_length = 15, blank=True, null=True)
    cpf = models.CharField(max_length = 11, blank=True, null=True)
    cnh = models.CharField(max_length = 11, blank=True, null=True)


    # Serve para definir o usuario como ativo ou nao, servindo de alternativa a uma exclusao
    # Nomeado "is_active" para seguir o padrao do django (utilizado, por exemplo, em User) 
    is_active = models.BooleanField(blank=False, null=False, default=True)

    #def __str__(self):
    #   return self.nome + " " + self.rg


# CONSIDERANDO AS OPERACOES CRUD, NAO UTILIZAR PARA CREATE, UPDATE E DELETE.
# Por ser apenas um proxy, ao efetuar buscas, tanto faz referenciar como "Usuario" 
# ou "User". No entanto, como "Usuario", eh possivel limitar o query selector a 
# buscar apenas usuarios ativos, utilizando o manager "actives".
class Usuario(User):
    # default manager
    objects = models.Manager()
    # custom
    actives = OnlyActive()

    class Meta:
        proxy = True

webserver/templates/cadastrar_pessoa_model_form.html
{% extends './main.html' %}
{% load static %}

    {% block page_content %}

        <section id="page-contents">
            <header class="content-top">
                <p>Cadastro de Desaparecido</p>
                <img src="{% static 'images/back-button.png' %}" onclick="history.back()">
            </header>
            <section class="form_container">
                <form method="POST" enctype="multipart/form-data" class="post-form">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="fields_container">
                        <div class="fields_left_column">
                            <p>Dados Pessoais</p>
                            {{ form.nome.errors }}
                            <div class="form_field">{{ form.nome.label_tag }}<span>{{ form.nome }}</span></div>
                            {{ form.sexo.errors }}
                            <div class="form_field">{{ form.sexo.label_tag }}<span>{{ form.sexo }}</span></div>
                            {{ form.data_nascimento.errors }}
                            <div class="form_field">{{ form.data_nascimento.label_tag }}<span>{{ form.data_nascimento }}</span></div>
                            {{ form.idade_aparente.errors }}
                            <div class="form_field">{{ form.idade_aparente.label_tag }}<span>{{ form.idade_aparente }}</span></div>
                            {{ form.nome_pai.errors }}
                            <div class="form_field">{{ form.nome_pai.label_tag }}<span>{{ form.nome_pai }}</span></div>
                            {{ form.nome_mae.errors }}
                            <div class="form_field">{{ form.nome_mae.label_tag }}<span>{{ form.nome_mae }}</span></div>
                            
                            <br>
                            <p>Aparência e Características</p>
                            {{ form.tipo_fisico.errors }}
                            <div class="form_field">{{ form.tipo_fisico.label_tag }}<span>{{ form.tipo_fisico }}</span></div>
                            {{ form.faixa_altura.errors }}
                            <div class="form_field">{{ form.faixa_altura.label_tag }}<span>{{ form.faixa_altura }}</span></div>
                            {{ form.cor_pele.errors }}
                            <div class="form_field">{{ form.cor_pele.label_tag }}<span>{{ form.cor_pele }}</span></div>
                            {{ form.cor_olhos.errors }}
                            <div class="form_field">{{ form.cor_olhos.label_tag }}<span>{{ form.cor_olhos }}</span></div>
                            {{ form.cor_cabelos.errors }}
                            <div class="form_field">{{ form.cor_cabelos.label_tag }}<span>{{ form.cor_cabelos }}</span></div>
                            {{ form.possui_tatuagem.errors }}
                            <div class="form_field">{{ form.possui_tatuagem.label_tag }}<span>{{ form.possui_tatuagem }}</span></div>
                            {{ form.possui_cicatriz.errors }}
                            <div class="form_field">{{ form.possui_cicatriz.label_tag }}<span>{{ form.possui_cicatriz }}</span></div>
                            {{ form.possui_deficiencia.errors }}
                            <div class="form_field">{{ form.possui_deficiencia.label_tag }}<span>{{ form.possui_deficiencia }}</span></div>
                            {{ form.sofreu_amputacao.errors }}
                            <div class="form_field">{{ form.sofreu_amputacao.label_tag }}<span>{{ form.sofreu_amputacao }}</span></div>
                        </div>
                        <div class="fields_right_column">
                            <div class="foto_fields_container">
                                <br>
                                {{ form.foto.errors }}
                                <div class="form_field">
                                    <p class="label-paragraph">Foto:</p>
                                    <!--{% if form.foto.name %}
                                    <img src="{{ form.foto.url }}" width="200" height="200" />
                                    {% else %}
                                    <img src="{% static 'images/no-photo-image.png' %}" width="200" height="200" />
                                    {% endif %}-->
                                    <img src="{% static 'images/no-photo-image.png' %}" width="200" height="200" />
                                    <br>
                                    {{ form.foto }}
                                    <label for="id_foto">ESCOLHER ARQUIVO</label>
                                    <span id='foto-file-name'></span>
                                    
                                    <p><!-- Gambiarra --></p>
                                    <br>
                                    <p class="label-paragraph">Cartazete:</p>
                                    {{ form.cartazete }}
                                    <label for="id_cartazete">ESCOLHER ARQUIVO</label>
                                    <span id='cartazete-file-name'></span>
                                    

                                    <p><!-- Gambiarra --></p>
                                    <br>
                                    <p class="label-paragraph">Nome no cartazete:</p>
                                    {{ form.nome_no_cartazete }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <p><!-- Gambiarra --></p>
                    <br>
                    <p>Sobre o Desaparecimento</p>
                    {{ form.data_desaparecimento.errors }}
                    <div class="form_field larger_form_field">{{ form.data_desaparecimento.label_tag }}<span>{{ form.data_desaparecimento }}</span></div>
                    {{ form.local_desaparecimento.errors }}
                    <div class="form_field larger_form_field">{{ form.local_desaparecimento.label_tag }}<span>{{ form.local_desaparecimento }}</span></div>
                    {{ form.local_desaparecimento.errors }}
                    <div class="form_field full_width_form_field">
                        {{ form.comentario_desaparecimento.label_tag }}
                        <br>
                        {{ form.comentario_desaparecimento }}
                    </div>

                    <br>
                    <div class="button-div"><button type="submit">CADASTRAR</button><div>
                </form>
            </section>
        </section>

    {% endblock %}

webserver/templates/cadastrar_usuario_model_form.html
{% extends './main.html' %}
{% load static %}

    {% block page_content %}
        <section id="page-contents">
            <header class="content-top">
                <p>Cadastro de Usuário</p>
                <img src="{% static 'images/back-button.png' %}" onclick="history.back()">
            </header>
            <section class="form_container">
                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {{ form.username.errors }}
                    <div class="form_field">{{ form.username.label_tag }}<span>{{ form.username }}</span></div>
                    {{ form.email.errors }}
                    <div class="form_field">{{ form.email.label_tag }}<span>{{ form.email }}</span></div>
                    {{ form.password.errors }}
                    <div class="form_field">{{ form.password.label_tag }}<span>{{ form.password }}</span></div>

                    <div class="button-div"><button type="submit">CADASTRAR</button></div>
                </form>
            </section>
        </section>
    {% endblock %}

webserver/templates/desaparecido.html
{% extends './main.html' %}
{% load static %}

    {% block page_content %}

        <section id="page-contents">
            <header class="content-top">
                <p>Detalhes do Desaparecido</p>
                <a href="{% url 'editarDesaparecido' pk=pessoa.pk %}" class="option-button link-button grey-on-hover">
                    <span>Editar</span><img src="{% static 'images/pencil-icon.png' %}">
                </a>
                <a href="{% url 'removerDesaparecido' pk=pessoa.pk %}" class="option-button link-button grey-on-hover">
                    <span>Excluir</span><img src="{% static 'images/black-x-icon.png' %}">
                </a>
                <img src="{% static 'images/back-button.png' %}" onclick="history.back()">
            </header>
            <section class="person_data_container">
                <div class="fields_container">

                    <div class="fields_left_column">
                        <p>Dados Pessoais</p>
                        <div class="data_field"><span class="space-to-the-right">Nome:</span><span class="grey-text">{{ pessoa.nome|default_if_none:"" }}</span></div>
                        <div class="data_field"><span class="space-to-the-right">Sexo:</span><span class="grey-text">{{ pessoa.sexo|default_if_none:"" }}</span></div>
                        <div class="data_field"><span class="space-to-the-right">Data de nascimento:</span><span class="grey-text">{{ pessoa.data_nascimento|default_if_none:"" }}</span></div>
                        <div class="data_field"><span class="space-to-the-right">Idade aparente:</span><span class="grey-text">{{ pessoa.get_idade_aparente_display|default_if_none:"" }}</span></div>
                        <div class="data_field"><span class="space-to-the-right">Nome do pai:</span><span class="grey-text">{{ pessoa.nome_pai|default_if_none:"" }}</span></div>
                        <div class="data_field"><span class="space-to-the-right">Nome da mãe:</span><span class="grey-text">{{ pessoa.nome_mae|default_if_none:"" }}</span></div>

                        <br>
                        <p>Aparência e Características</p>
                        <div class="data_field"><span class="space-to-the-right">Tipo físico:</span><span class="grey-text">{{ pessoa.tipo_fisico }}</span></div>
                        <div class="data_field"><span class="space-to-the-right">Faixa de altura:</span><span class="grey-text">{{ pessoa.get_faixa_altura_display|default_if_none:"" }}</span></div>
                        <div class="data_field"><span class="space-to-the-right">Cor da pele:</span><span class="grey-text">{{ pessoa.cor_pele|default_if_none:"" }}</span></div>
                        <div class="data_field"><span class="space-to-the-right">Cor dos olhos:</span><span class="grey-text">{{ pessoa.cor_olhos|default_if_none:"" }}</span></div>
                        <div class="data_field"><span class="space-to-the-right">Cor do cabelo:</span><span class="grey-text">{{ pessoa.cor_cabelos|default_if_none:"" }}</span></div>
                        <div class="data_field"><span class="space-to-the-right">Possui tatuagem?</span><span class="grey-text">{% if pessoa.possui_tatuagem %}Sim{% else %}Nao{% endif %}</span></div>
                        <div class="data_field"><span class="space-to-the-right">Possui cicatriz?</span><span class="grey-text">{% if pessoa.possui_cicatriz %}Sim{% else %}Nao{% endif %}</span></div>
                        <div class="data_field"><span class="space-to-the-right">Possui deficiência?</span><span class="grey-text">{% if pessoa.possui_deficiencia %}Sim{% else %}Nao{% endif %}</span></div>
                        <div class="data_field"><span class="space-to-the-right">Sofreu amputação?</span><span class="grey-text">{% if pessoa.sofreu_amputacao %}Sim{% else %}Nao{% endif %}</span></div>
                    </div>
                    <div class="fields_right_column">
                        <div class="foto_fields_container">
                            <div class="data_field">
                                <p class="label-paragraph">Foto:</p>
                                {% if pessoa.foto.name %}
                                <img src="{{ pessoa.foto.url }}" width="300" height="300" />
                                {% else %}
                                <img src="{% static 'images/no-photo-image.png' %}" width="200" height="200" />
                                {% endif %}
                                <br>

                                <p><!-- Gambiarra --></p>
                                <br>
                                {% if pessoa.foto.name %}
                                <p class="label-paragraph">Cartazete:</p>
                               <div class="container" id = "container" >
                                  <img src="{% static 'images/cartazpreto.jpg' %}" style="max-height: 400px;max-width:300px;" id="cartazete" />
                                  <div class="info" id="info" >
                                    <div class="idade" id="idade"><p class="infodes" style="font-size: 11px" >Idade: {{ pessoa.idade_aparente }}</p></div>
                                    <div class="quando" id="quando"><p class="infodes" style="font-size: 11px">Desaparecimento: {{ pessoa.data_desaparecimento }}</p></div>
                                    <div class="local" id="local"><p class="infodes" style="font-size: 11px">Local: {{ pessoa.local_desaparecimento }}</p></div>
                                </div>
                                <div class="nome" id="nome"><p style="font-size:15px">{{ pessoa.nome }}</p></div>
                                <div class="foto" id="foto"><img src = "{{ pessoa.foto.url }}" style="max-height: 120px;max-width:120px;"></div>
                               </div>

                               <div class="button-div" onclick="capturar()"><button type="submit">Baixar cartaz</button>

                               </div><br>
                               <p>Guardar cartaz:</p>
                                <input type="file" id="input_img" onchange="fileChange()" accept="image/*"><br>
                                <script src="https://code.jquery.com/jquery-2.0.3.min.js" type="text/javascript" ></script>
                                 <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.5.0-beta4/html2canvas.min.js"></script>
                                 <script type="text/javascript">
                                   function capturar(){
                                        var divImagem = document.getElementById("container");
                                        html2canvas(divImagem).then(function(canvas) {
                                        var imagem = canvas.toDataURL("image/png").replace("image/png", "image/octet-stream");
                                        var a = document.createElement('a');
                                        a.href = imagem;
                                        a.download = '{{ pessoa.nome }}.png';
                                        //a.src = 'data:image/png;base64,' + imagem;
                                        a.click();
                                        //fileChange(a);
                                  });
                                }
                                function fileChange(){
                                  var file = document.getElementById('input_img');
                                  var form = new FormData();
                                  form.append("image", file.files[0])

                                  var settings = {
                                    "url": "https://api.imgbb.com/1/upload?key=8765818615b1a206c788c8a3d26f52e0",
                                    "method": "POST",
                                    "timeout": 0,
                                    "processData": false,
                                    "mimeType": "multipart/form-data",
                                    "contentType": false,
                                    "data": form
                                  };


                                  $.ajax(settings).done(function (response) {
                                    console.log(response);
                                    var jx = JSON.parse(response);
                                    console.log(jx.data.url);
                                    let array = jx.data.image.url.split("/");
                                    let code = array[3];
                                    let nome = array[4].split(".");
                                    let nomecartaz = code+"/"+nome[0];
                                    console.log(nomecartaz);
                                    let url = "{% url 'editarNomeCartazete' pk=pessoa.pk %}"+"?nomecartazete="+nomecartaz;
                                    window.location.href = url;

                                  });

                                  /*

                                  console.log(url);
                                  var request = {
                                    "url": url,
                                    "method": "GET",
                                    "nomecartazete": nomecartaz
                                  };
                                  $.ajax(request).done(function (response) {
                                    console.log(response);
                                  });
                                  */
                                }
                                 </script>
                                 {% else %}
                                 <img src="{% static 'images/no-cartazete.png' %}" style="max-height: 500px;max-width:200px;" id="cartazete" />
                                 {% endif %}

                                <p><!-- Gambiarra --></p>
                                <br>
                                <p class="label-paragraph">Nome no cartazete:</p>
                                {% if pessoa.nome_no_cartazete %}
                                <span class="grey-text">{{ pessoa.nome_no_cartazete }}</span>
                                {% else %}
                                <span class="grey-text">Sem nome no cartazete</span>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <p><!-- Gambiarra --></p>
                    <br>
                    <p>Sobre o Desaparecimento</p>
                    <div class="data_field larger_form_field"><span class="space-to-the-right">Data do desaparecimento:</span><span class="grey-text">{{ pessoa.data_desaparecimento|default_if_none:"" }}</span></div>
                    <div class="data_field larger_form_field"><span class="space-to-the-right">Local do desaparecimento:</span><span class="grey-text">{{ pessoa.local_desaparecimento|default_if_none:"" }}</span></div>
                    <div class="data_field full_width_form_field">
                        Comentário sobre o desaparecimento:
                        <br>
                        <span class="grey-text">{{ pessoa.comentario_desaparecimento|default_if_none:"" }}</span>
                    </div>
                </div>




            </section>
        </section>

    {% endblock %}

webserver/templates/desaparecidos.html
{% extends './main.html' %}
{% load static %}

    {% block page_content %}
        <section id="page-contents">
            <header class="content-top">
                <p>Desaparecidos</p>
                <img src="{% static 'images/back-button.png' %}" onclick="history.back()">
            </header>
            <section id="button-container">
                <div id="register-button" class="grey-on-hover">
                    <a href="{% url 'cadastrarDesaparecido' %}" class="button-link">
                        <div class="button-text-container">
                            <p class="button-title">CADASTRO</p>
                            <p class="button-subtitle">Clique para cadastrar um desaparecido</p>
                        </div>
                        <img class="button-icon" src="{% static 'images/black-circle-plus-icon.png' %}">
                    </a>
                </div>

                <div id="search-button" class="grey-on-hover">
                    <a href="{% url 'buscarDesaparecidoWeb' %}" class="button-link">
                        <div class="button-text-container">
                            <p class="button-title">BUSCAR</p>
                            <p class="button-subtitle">Clique para buscar um desaparecido</p>
                        </div>
                        <img class="button-icon" src="{% static 'images/black-magnifier-icon.png' %}">
                    </a>
                </div>
            </section>
            <section class="results-grid">
                {% if results %}
                {% for result in results %}
                    <div class="result person-result">
                        <div class="result-contents">
                            {% if result.foto %}
                            <img src="{{ result.foto.url }}" class="result-photo" />
                            {% else %}
                            <img src="{% static 'images/user-icon.png' %}" class="dummy-photo" />
                            {% endif %}
                            <a href="{% url 'editarDesaparecido' pk=result.pk %}" class="option-button link-button grey-on-hover">
                                <p>Editar</p><img src="{% static 'images/pencil-icon.png' %}">
                            </a>
                            <a href="#" onclick = "overlay('{% url 'removerDesaparecido' pk=result.pk %}')" class="option-button link-button grey-on-hover">
                                <p>Excluir</p><img src="{% static 'images/black-x-icon.png' %}">
                            </a>
                            <p class="name">{{ result.nome }}</p>
                        </div>
                        <div class=result-details-option>
                            <a href="{% url 'visualizarDesaparecido' pk=result.pk %}" class="option-button"><img src="{% static 'images/white-plus-icon.png' %}"><p>Detalhes</p></a>
                        </div>
                    </div>
                    <script>
                        function overlay(link) {
                            var resultado = confirm("Você realmente quer apagar este desaparecido?");
                            if(resultado){
                                window.location.href = link;
                            }
                       }
                    </script>
                {% endfor %}
            {% else %}
                <p>Nenhum desaparecido encontrado.</p>
            {% endif %}

            </section>
        </section>
    {% endblock %}